# Generated by Django 4.1.3 on 2022-12-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('cname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('pnumber', models.IntegerField()),
            ],
        ),
    ]
